image: docker:latest

variables:
  DOCKER_HOST: unix:///var/run/docker.sock
  POSTGRES_DB: offendertracker
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: senha123

stages:
  - test
  - package
  - image
  - deploy

services:
  - name: postgres:latest
    alias: db

cache:
  paths:
    - .m2/repository

test:
  stage: test
  image: eletraenergy/maven:3.8-openjdk-17-slim
  retry: 2
  script:
    - echo "DATABASE_URL=$DATABASE_URL"
    - echo "DB_USER=$DB_USER"
    - echo "DB_PASSWORD=$DB_PASSWORD"
    - mvn -T 1C --batch-mode --no-transfer-progress test
  tags:
    - docker
  artifacts:
    when: always
    reports:
      junit:
        - production.manager/target/surefire-reports/TEST-*.xml
        - production.manager/target/failsafe-reports/TEST-*.xml

package:
  stage: package
  image: eletraenergy/maven:3.8-openjdk-17-slim
  retry: 2
  script:
    - mvn -DskipTests=true --batch-mode --no-transfer-progress clean package
  artifacts:
    paths:
      - target/*.jar
  tags:
    - docker

images:
  stage: image
  script:
    - apk add git
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker build -t eletraenergy/offenders-backend:latest .
    - docker push eletraenergy/offenders-backend:latest
  tags:
    - docker

deploy:
  stage: deploy
  script:
    - apk add --no-cache curl
    - apk add --no-cache docker-compose
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker-compose -f docker-compose.yml pull
    - docker-compose -f docker-compose.yml up -d
  when: manual
  tags:
    - shanghai

