version: '3'
services:
  app:
    build: .
    ports:
      - "8082:8081"
    depends_on:
      - db
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/offendertracker
      - DB_USER=postgres
      - DB_PASSWORD=senha123

  db:
    image: postgres
    environment:
      - POSTGRES_DB=offendertracker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=senha123
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    image: eletraenergy/offenders-frontend
    ports:
      - "9440:80"
    container_name: offender-frontend
    depends_on:
      - app

volumes:
  postgres_data:
