image: docker:latest

variables:
  DOCKER_HOST: unix:///var/run/docker.sock

stages:
  - test
  - package
  - build
  - deploy

test:
  stage: test
  image: maven:3.8.5-openjdk-17
  script:
    - mvn test
  tags:
    - docker

package:
  stage: package
  image: maven:3.8.5-openjdk-17
  script:
    - mvn -DskipTests=true clean package
  artifacts:
    paths:
      - target/*.jar
  tags:
    - docker

build:
  stage: build
  script:
    - apk add --no-cache git
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker build -t myapp:latest .
    - docker push myapp:latest
  only:
    - main
  tags:
    - docker

deploy:
  stage: deploy
  script:
    - apk add --no-cache curl docker-compose
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker-compose -f docker-compose.yml up -d
  when: manual
  only:
    - main
  tags:
    - docker
