version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8081"
    depends_on:
      - db
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/offendertracker
      - DB_USER=postgres
      - DB_PASSWORD=senha123

  db:
    image: postgres
    environment:
      - POSTGRES_DB=offendertracker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=senha123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
